language: cpp

os: linux
dist: bionic

compiler:
  - g++
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - g++
      - gcc
      - clang
      - cppcheck

script:
  - cd build
  - cmake ..
  - make
  - ctest -V
  - cppcheck --error-exitcode=1 src/
  - cppcheck --error-exitcode=1 build/tests/
