language: cpp

os: linux
dist: bionic

compiler:
  - g++
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - g++
      - gcc
      - clang

script:
  - cd build
  - cmake ..
  - make
  - ctest -V
