language: cpp

os: linux
dist: bionic

compiler:
  - g++
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - g++
      - gcc
      - clang
      - cppcheck

script:
  - cd build
  - cmake ..
  - make -j4
  - ctest -V
  - cd ..
  - cppcheck --error-exitcode=1 src/
  - cppcheck --error-exitcode=1 build/tests/
  - ./build/src/app/asn1c -a examples/TestModule.asn1 -p
