language: cpp

os: linux
dist: bionic

compiler:
  - g++
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-7
      - gcc-7
      - clang-6.0

script:
  - cd build
  - cmake ..
  - make
  - ctest -V
