#pragma once

namespace OpenASN
{
  enum class Production
  {
    ASSIGNMENT,
    ASSIGNMENT_LIST,
    BOOLEAN_TYPE,
    BUILTIN_TYPE,
    COMPONENT_TYPE,
    COMPONENT_TYPE_LIST,
    COMPONENT_TYPE_LISTS,
    DEFINITIVE_IDENTIFICATION,
    DEFINITIVE_OID,
    DEFINITIVE_OBJ_ID_COMPONENT,
    DEFINITIVE_OBJ_ID_COMPONENT_LIST,
    IDENTIFIER,
    INTEGER_TYPE,
    MODULE_BODY,
    MODULE_DEFINITION,
    MODULE_IDENTIFIER,
    MODULE_REFERENCE,
    NAME_FORM,
    NAMED_TYPE,
    ROOT_COMPONENT_TYPE_LIST,
    SEQUENCE_TYPE,
    TYPE,
    TYPE_ASSIGNMENT,
    TYPE_REFERENCE,
    VALUE_REFERENCE
  };
}
