ModuleBody ::=
    AssignmentList
  | empty

-- LOCAL ADDITION
-- This production is not present in spec and is added locally to facilicate
-- parsing
Absent ::= "ABSENT"

AdditionalElementSetSpec ::= ElementSetSpec

-- ORDERING CRITICAL
-- Ordering is critical here and should be exactly as shown here.
-- The longer production group with comma is to be tried first.
-- Also within that production group NamedType is to be tried first to
-- avoid going into a infinite recursion.
AlternativeTypeList ::= NamedType "," AlternativeTypeList | NamedType

AlternativeTypeLists ::= RootAlternativeTypeList

-- LOCAL ADDITION
Application ::= "APPLICATION"

ArcIdentifier ::= integerUnicodeLabel | non-integerUnicodeLabel

Assignment ::= TypeAssignment

-- ORDERING CRITICAL
AssignmentList ::= Assignment AssignmentList | Assignment

-- ORDERING CRITICAL
-- LOCAL MODIFICATION
-- Converted BIT and STRING to string data type
BitStringType ::= "BIT" "STRING" "{" NamedBitList "}" | "BIT" "STRING"




DateTimeType ::= "DATE-TIME"

ValueRange ::= LowerEndpoint ".." UpperEndpoint
