TestModule DEFINITIONS ::=
BEGIN

Bool                  ::= BOOLEAN
BitStr1               ::= BIT STRING { a(0), b(1), c(100) }
BitStr2               ::= BIT STRING
CharStr1              ::= BMPString
CharStr2              ::= GeneralString
CharStr3              ::= GraphicString
CharStr4              ::= IA5String
CharStr5              ::= ISO646String
CharStr6              ::= NumericString
CharStr7              ::= PrintableString
CharStr8              ::= TeletexString
CharStr9              ::= T61String
CharStr10             ::= UniversalString
CharStr11             ::= UTF8String
CharStr12             ::= VideotexString
CharStr13             ::= VisibleString
CharStr14             ::= CHARACTER STRING

Choice                ::= CHOICE {
  chInt                 INTEGER,
  chBool                BOOLEAN
}

Date                  ::= DATE
DateTime              ::= DATE-TIME
Duration              ::= DURATION
EmbeddedPDV           ::= EMBEDDED PDV
Enumerated1           ::= ENUMERATED { a, b, c, d }
Enumerated2           ::= ENUMERATED { w(-1), x(0), y(1), z(2) }
External              ::= EXTERNAL
Int1                  ::= INTEGER
Int2                  ::= INTEGER { w(-1), x(0), y(1), z(2) }
Iri                   ::= OID-IRI
Null                  ::= NULL
ObjId                 ::= OBJECT IDENTIFIER
OctetStr              ::= OCTET STRING
Real                  ::= REAL
RelativeIri           ::= RELATIVE-OID-IRI
RelativeOid           ::= RELATIVE-OID

Sequence              ::= SEQUENCE {
  seqBool               BOOLEAN,
  seqBitStr1            BIT STRING { a(0), b(1), c(100) },
  seqBitStr2            BIT STRING,
  seqBitStr3            BIT STRING DEFAULT '1010'B,
  seqBitStr4            BIT STRING DEFAULT { abc, def },
  seqBitStr5            BIT STRING DEFAULT CONTAINING '00FF'H,
  seqCharStr1           BMPString,
  seqCharStr2           GeneralString,
  seqCharStr3           GraphicString,
  seqCharStr4           IA5String,
  -- RestrictedCharacterStringValue->Tuple
  seqCharStr4Tuple      IA5String DEFAULT { 2, 3 },
  seqCharStr5           ISO646String,
  seqCharStr6           NumericString,
  seqCharStr7           PrintableString,
  seqCharStr8           TeletexString,
  seqCharStr9           T61String,
  seqCharStr10          UniversalString,
  -- RestrictedCharacterStringValue->cstring
  seqCharStr10Cstr      UniversalString DEFAULT "ABCD",
  -- RestrictedCharacterStringValue->Quadruple
  seqCharStr10Quad      UniversalString DEFAULT { 10, 11, 12, 13 },
  -- RestrictedCharacterStringValue->CharacterStringList->cstring
  seqCharStr10StrList   UniversalString DEFAULT { "ABCD", "DEFG" },
  -- RestrictedCharacterStringValue->CharacterStringList->Quadruple
  seqCharStr10StrList   UniversalString DEFAULT {
                          { 10, 11, 12, 13 },
                          { 14, 15, 16, 17 }
                        },
  -- RestrictedCharacterStringValue->CharacterStringList->DefinedValue
  seqCharStr10StrList   UniversalString DEFAULT { abcd, defg },
  seqCharStr11          UTF8String,
  seqCharStr12          VideotexString,
  seqCharStr13          VisibleString,
  seqCharStr14          CHARACTER STRING,
  -- TODO UnrestrictedCharacterStringValue, NamedValue
  seqCharStr14StrVal    CHARACTER STRING DEFAULT {
                          --identification presentation-context-id:5
                          string-value '66'H
                        },
  seqCh1                CHOICE { i INTEGER, b BOOLEAN },
  seqCh2                CHOICE { i INTEGER, b BOOLEAN } DEFAULT b : TRUE,
  seqDate               DATE,
  seqDateTime           DATE-TIME,
  seqDuration           DURATION,
  seqEmbeddedPDV        EMBEDDED PDV,
  seqEnumerated1        ENUMERATED { a, b, c, d },
  seqEnumerated2        ENUMERATED { w(-1), x(0), y(1), z(2) },
  seqInt1               INTEGER,
  seqInt2               INTEGER { w(-1), x(0), y(1), z(2) },
  seqIri                OID-IRI,
  seqNull               NULL,
  seqObjId              OBJECT IDENTIFIER,
  seqOctetStr           OCTET STRING,
  seqReal               REAL,
  seqRelativeIri        RELATIVE-OID-IRI,
  seqRelativeOid        RELATIVE-OID,
  seqSeqOf1             SEQUENCE OF INTEGER,
  seqSeqOf2             SEQUENCE OF INTEGER { w(-1), x(0), y(1), z(2) },
  seqSeqOf3             SEQUENCE OF seqSeqOf3Int INTEGER {
                          w(-1),
                          x(0),
                          y(1),
                          z(2)
                        }
}

Sequence1             ::= SEQUENCE {
  COMPONENTS OF Sequence,
  seq1Int               INTEGER
}

SeqOf1                ::= SEQUENCE OF INTEGER
SeqOf2                ::= SEQUENCE OF INTEGER { w(-1), x(0), y(1), z(2) }
SeqOf3                ::= SEQUENCE OF seqOf3Int INTEGER {
                            w(-1),
                            x(0),
                            y(1),
                            z(2)
                          }

Set                   ::= SET {
  setBool               BOOLEAN,
  setBitStr1            BIT STRING { a(0), b(1), c(100) }
}

SetOf1                ::= SET OF INTEGER
SetOf2                ::= SET OF INTEGER { w(-1), x(0), y(1), z(2) }
SetOf3                ::= SET OF prefSetOf3Int INTEGER {
                            w(-1),
                            x(0),
                            y(1),
                            z(2)
                          }
Prefixed1             ::= [TAG : APPLICATION 5] IMPLICIT INTEGER
Prefixed2             ::= [PRIVATE 5] EXPLICIT INTEGER
Prefixed3             ::= [5] INTEGER
Prefixed4             ::= [PrefAbcModule.prefExtValueRef] INTEGER {
                            w(-1),
                            x(0),
                            y(1),
                            z(2)
                          }
Prefixed5             ::= [localValueRef] SET OF INTEGER {
                            w(-1),
                            x(0),
                            y(1),
                            z(2)
                          }
Prefixed6             ::= [TAG :] INTEGER
Time                  ::= TIME
TimeOfDay             ::= TIME-OF-DAY

DefinedType1          ::= DefAbcModule.DefExtTyperef
DefinedType2          ::= Prefixed1
UsefulType1           ::= GeneralizedTime
UsefulType2           ::= UTCTime
UsefulType3           ::= ObjectDescriptor

SelectionType         ::= chInt < Choice

-- TODO check precedence of EXCEPT ^ | 50.1 note 2
--SingleValue
SvConstrainedType1    ::= BOOLEAN (TRUE)
-- Two constraints (recursive)
SvConstrainedType2    ::= BOOLEAN (TRUE) (TRUE)
SvConstrainedType3    ::= BOOLEAN (TRUE ^ FALSE EXCEPT TRUE)
SvConstrainedType4    ::= BOOLEAN (TRUE | FALSE EXCEPT FALSE)
SvConstrainedType5    ::= BOOLEAN (TRUE ^ FALSE | FALSE ^ TRUE EXCEPT FALSE)
SvConstrainedType6    ::= BOOLEAN (TRUE , ... )
SvConstrainedType7    ::= BOOLEAN (TRUE , ... ! BOOLEAN : FALSE)
SvConstrainedType8    ::= BOOLEAN (TRUE , ... , FALSE)
SvConstrainedType9    ::= BOOLEAN (ALL EXCEPT TRUE)
SvConstrainedType10   ::= BOOLEAN (TRUE , ... , ALL EXCEPT FALSE)
SvConstrainedType11   ::= BOOLEAN (TRUE , ... , FALSE ! BOOLEAN : FALSE)
SvConstrainedType12   ::= BOOLEAN (TRUE , ... , FALSE EXCEPT TRUE ! BOOLEAN : FALSE)
SvConstrainedType13   ::= BIT STRING ('1100 0101'B | 'ABCD 1010'H)

--ContainedSubtype
CsConstrainedType1    ::= BOOLEAN (INCLUDES BOOLEAN)
CsConstrainedType2    ::= BOOLEAN (BOOLEAN)

--ValueRange
VrConstrainedType1    ::= BOOLEAN (MIN..MAX)
VrConstrainedType2    ::= INTEGER (-100..100)

--SizeConstraint
ScConstrainedType1    ::= BIT STRING (SIZE (10))
ScConstrainedType2    ::= BIT STRING (SIZE (0..10))

--PermittedAlphabet
-- TODO Change to meaningful constraints
PaConstrainedType1    ::= NumericString (FROM (TRUE | FALSE | TRUE))
PaConstrainedType2    ::= NumericString (BOOLEAN (INCLUDES BOOLEAN))
PaConstrainedType3    ::= NumericString (INTEGER (-100..100))
PaConstrainedType4    ::= NumericString (BIT STRING (SIZE (0..10)))

--TypeConstraint
TcConstrainedType1    ::= NumericString (BOOLEAN | INTEGER)

--InnerTypeConstraints
-- https://www.obj-sys.com/asn1tutorial/node18.html
ItcSeqOf1             ::= SEQUENCE OF INTEGER
-- Can only be applied to restrict set-of, sequence-of types
ItcConstrainedType1   ::= ItcSeqOf1 (WITH COMPONENT (-100..100))
ItcSeq1               ::= SEQUENCE {
  a                     BOOLEAN DEFAULT TRUE,
  b                     INTEGER OPTIONAL
}

ItcConstrainedType2   ::= ItcSeq1 (WITH COMPONENTS {
                            a (TRUE | FALSE),
                            b
                          })
-- Can only be applied to restrict set, sequence and choice types
ItcConstrainedType3   ::= ItcSeq1 (WITH COMPONENTS {
                            ...,
                            a (TRUE | FALSE),
                            b ABSENT
                          })

--PatternConstraint
PcConstrainedType1    ::= BOOLEAN (PATTERN TRUE)

--PropertySettings
PsConstrainedType1    ::= DATE (SETTINGS "Basic=Date Date=YMD")
PsConstrainedType2    ::= TIME (SETTINGS "Midnight=Start")

END
