TestModule DEFINITIONS ::=
BEGIN

Bool              ::= BOOLEAN
BitStr1           ::= BIT STRING { a(0), b(1), c(100) }
BitStr2           ::= BIT STRING
CharStr1          ::= BMPString
CharStr2          ::= GeneralString
CharStr3          ::= GraphicString
CharStr4          ::= IA5String
CharStr5          ::= ISO646String
CharStr6          ::= NumericString
CharStr7          ::= PrintableString
CharStr8          ::= TeletexString
CharStr9          ::= T61String
CharStr10         ::= UniversalString
CharStr11         ::= UTF8String
CharStr12         ::= VideotexString
CharStr13         ::= VisibleString
CharStr14         ::= CHARACTER STRING

Ch ::= CHOICE {
  chInt                 INTEGER,
  chBool                BOOLEAN
}

Date              ::= DATE
DateTime          ::= DATE-TIME
Duration          ::= DURATION
EmbeddedPDV       ::= EMBEDDED PDV
Enumerated1       ::= ENUMERATED { a, b, c, d }
Enumerated2       ::= ENUMERATED { w(-1), x(0), y(1), z(2) }
External          ::= EXTERNAL
Int1              ::= INTEGER
Int2              ::= INTEGER { w(-1), x(0), y(1), z(2) }
Iri               ::= OID-IRI
Null              ::= NULL
ObjId             ::= OBJECT IDENTIFIER
OctetStr          ::= OCTET STRING
Real              ::= REAL
RelativeIri       ::= RELATIVE-OID-IRI
RelativeOid       ::= RELATIVE-OID

Seq ::= SEQUENCE {
  seqBool              BOOLEAN,
  seqBitStr1           BIT STRING { a(0), b(1), c(100) },
  seqBitStr2           BIT STRING,
  seqCharStr1          BMPString,
  seqCharStr2          GeneralString,
  seqCharStr3          GraphicString,
  seqCharStr4          IA5String,
  seqCharStr5          ISO646String,
  seqCharStr6          NumericString,
  seqCharStr7          PrintableString,
  seqCharStr8          TeletexString,
  seqCharStr9          T61String,
  seqCharStr10         UniversalString,
  seqCharStr11         UTF8String,
  seqCharStr12         VideotexString,
  seqCharStr13         VisibleString,
  seqCharStr14         CHARACTER STRING,
  seqCh CHOICE {
    i INTEGER,
    b BOOLEAN
  },
  seqDate              DATE,
  seqDateTime          DATE-TIME,
  seqDuration          DURATION,
  seqEmbeddedPDV       EMBEDDED PDV,
  seqEnumerated1 ENUMERATED { a, b, c, d },
  seqEnumerated2 ENUMERATED { w(-1), x(0), y(1), z(2) },
  seqInt1              INTEGER,
  seqInt2              INTEGER { w(-1), x(0), y(1), z(2) },
  seqIri               OID-IRI,
  seqNull              NULL,
  seqObjId             OBJECT IDENTIFIER,
  seqOctetStr          OCTET STRING,
  seqReal              REAL,
  seqRelativeIri       RELATIVE-OID-IRI,
  seqRelativeOid       RELATIVE-OID
}

END
